port: 9001
jwt:
  secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
sqs:
  region: us-west2
  endpoint: http://localhost:4566
sns:
  region: us-west2
  endpoint: http://localhost:4566
events:
  items-created: items-created
  items-updated: items-updated
  items-lock-requested: items-lock-requested
  items-lock-completed: items-lock-completed
