port: 9003
jwt:
  secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
mongodb:
  database: trades
  connection_string: mongodb://0.0.0.0:27017
inventory_service:
  url: localhost:9005
